server:
  port: 8080
  servlet:
    context-path: /cn
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 122333zwz
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    protocol: smtp
    host: smtp.163.com
    port: 25
    username: zwz3228397889@163.com
    password: QBRQHLIAYPEMEIVB
    default-encoding: utf-8
    properties:
      mail:
        debug: true
mybatis:
  mapper-locations:
    - classpath:mybatis/*.xml